services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trx
      MYSQL_USER: app
      MYSQL_PASS: app
    volumes:
      - ~/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
