version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.2
    container_name: zg_core_zookeeper
    restart: always
    volumes:
      - zg_core_zookeeper_data:/var/lib/zookeeper/data
      - zg_core_zookeeper_logs:/var/lib/zookeeper/log
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:5.1.2
    container_name: zg_core_kafka
    restart: always
    volumes:
      - zg_core_kafka_data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    ports:
      # Exposes 9092 for external connections to the broker and routes it to 29092
      # Use kafka:9092 for connections internal on the docker network
      - 9092:29092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

  schemaregistry:
    image: confluentinc/cp-schema-registry:5.1.2
    container_name: zg_core_schema_registry
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schemaregistry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
    ports:
      - 8081:8081

volumes:
  zg_core_zookeeper_data:
    driver: local
  zg_core_zookeeper_logs:
    driver: local
  zg_core_kafka_data:
    driver: local