version: '3.1'
services:
  perfstub_postgres:
    container_name: perfstub-postgres
    image: postgres
    restart: always
    user: "postgres"
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
    volumes:
      - ./db_script/init.sql:/docker-entrypoint-initdb.d/db.sql
      - C:\\temp\\postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432